EbuyProject/ViewModels/ElectronicsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Ebuy.Model.Common;

namespace EbuyProject.ViewModels
{
    public class ElectronicsViewModel
    {
        public int ElectronicPartId { get; set; } // ElectronicPartId (Primary key)
        public string ElectronicPartName { get; set; } // ElectronicPartName (length: 50)
        public string ElectronicPartDescription { get; set; } // ElectronicPartDescription
        public int? ElectronicPartPrice { get; set; } // ElectronicPartPrice
       public int? CartId { get; set; } // CartId

        // Foreign keys
        public virtual ICart Cart { get; set; } // FK_Electronic_Cart
    }
}

EbuyProject/Controllers/ElectronicController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Ebuy.Model.Common;
using Ebuy.Repository.Config;
using Ebuy.Service.Common;
using EbuyProject.ViewModels;

namespace EbuyProject.Controllers
{
    public class ElectronicController : Controller
    {
        public ElectronicController(IElectronicsService service)
        {
            this.Service = service;
        }
        private readonly IElectronicsService Service;
        // GET: Electronic
        public async Task<ActionResult> Index(string search, string sortBy, int page = 1)
        {
            ViewBag.sortNameParameter = string.IsNullOrEmpty(sortBy) ? SortingOperations.Descending : SortingOperations.Ascending;
            return View(AutoMapper.Mapper.Map<IList<ElectronicsViewModel>>(await Service.GetAllAsync(search, page, sortBy)));
        }
        public ActionResult Add()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Add([Bind(Include = "ElectronicPartName,ElectronicPartPrice,ElectronicPartDescription")] ElectronicsViewModel electronic)
        {
            if (ModelState.IsValid)
            {
                await Service.AddAsync(AutoMapper.Mapper.Map<IElectronics>(electronic));
                return RedirectToAction("Index");
            }
            return View(electronic);
        }

        public async Task<ActionResult> Delete(int? id)
        {
            if (await Service.GetAsync(id) == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            return View(AutoMapper.Mapper.Map<ElectronicsViewModel>(await Service.GetAsync(id)));
        }

        [HttpPost, ActionName("Delete")]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await Service.RemoveAsync(await Service.GetAsync(id));
            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Details(int id)
        {
            if (await Service.GetAsync(id) == null)
            {
                return HttpNotFound();
            }
            return View(AutoMapper.Mapper.Map<ElectronicsViewModel>(await Service.GetAsync(id)));
        }

        public async Task<ActionResult> Edit(int id)
        {
            if (await Service.GetAsync(id) == null)
            {
                return HttpNotFound();
            }
            return View(AutoMapper.Mapper.Map<ElectronicsViewModel>(await Service.GetAsync(id)));
        }

        [HttpPost, ActionName("Edit")]
        public async Task<ActionResult> Edit([Bind(Include = "ElectronicPartId,ElectronicPartName,ElectronicPartPrice,ElectronicPartDescription")] ElectronicsViewModel electronic)
        {
            if (ModelState.IsValid)
            {
                await Service.UpdateAsync(AutoMapper.Mapper.Map<IElectronics>(electronic));
                return RedirectToAction("Index");
            }
            return View(electronic);
        }
    }
}

EbuyProject/Views/Electronic/Add.cshtml
@model EbuyProject.ViewModels.ElectronicsViewModel

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ElectronicsViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

EbuyProject/Views/Electronic/Delete.cshtml
@model EbuyProject.ViewModels.ElectronicsViewModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>ElectronicsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

EbuyProject/Views/Electronic/Details.cshtml
@model EbuyProject.ViewModels.ElectronicsViewModel

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>ElectronicsViewModel</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartDescription)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartDescription)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ElectronicPartPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ElectronicPartPrice)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

EbuyProject/Views/Electronic/Edit.cshtml
@model EbuyProject.ViewModels.ElectronicsViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ElectronicsViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ElectronicPartId)
        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartDescription, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartDescription, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartDescription, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElectronicPartPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElectronicPartPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElectronicPartPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

EbuyProject/Views/Electronic/Index.cshtml
@model IEnumerable<EbuyProject.ViewModels.ElectronicsViewModel>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Add")
</p>
<p>
    @using (Html.BeginForm("Index", "Electronic", FormMethod.Get))
    {
        @Html.TextBox("search") <input type="submit" value="Search Electronic By Name" />
    }
</p>
<table class="table">
    <tr>
        <th>
            @Html.ActionLink("Electronic Part Name", "Index", new { sortBy = ViewBag.sortNameParameter, search = Request.QueryString["search"] })
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ElectronicPartPrice)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ElectronicPartDescription)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ElectronicPartName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ElectronicPartPrice)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ElectronicPartDescription)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.ElectronicPartId }) |
            @Html.ActionLink("Details", "Details", new { id = item.ElectronicPartId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.ElectronicPartId })
        </td>
    </tr>
}

</table>
<input type="button" value="1" onclick="location.href='@Url.Action("Index", "Electronic", new { page = 1 } )'" />
<input type="button" value="2" onclick="location.href='@Url.Action("Index", "Electronic", new { page = 2 } )'" />
<input type="button" value="3" onclick="location.href='@Url.Action("Index", "Electronic", new { page = 3 } )'" />
<!-- izmisliti bolji nacin numeriranja  -->